services:
  # Cerveau / Orchestrateur
  flowise:
    image: flowiseai/flowise:latest
    container_name: jarvis_brain_flowise
    restart: unless-stopped
    ports:
      - "3000:3000"
    volumes:
      - flowise_data:/root/.flowise
    networks:
      - jarvis_net

  # Frontend / Interface Utilisateur 
  frontend:
    container_name: jarvis_ui_nextjs
    restart: unless-stopped
    build:
      context: ./jarvis-frontend 
      dockerfile: Dockerfile
    ports:
      - "80:3000" 
    networks:
      - jarvis_net
    depends_on:
      - flowise

volumes:
  flowise_data:

networks:
  jarvis_net:
    driver: bridge